service: serverless-mailgun-slack

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: ap-northeast-1
  environment:
    MAILGUN_API_KEY: ${file(./secrets.yml):mailgun_api_key}
    SLACK_WEBHOOK_URL: ${file(./secrets.yml):slack_webhook_url}

functions:
  ping: {handler: handler.ping}
  mailgunCallback:
    handler: handler.mailgunCallback
    events:
      - http:
          path: callback
          method: post
